### ISSUE TITLE
AP Invoice Layout

### ISSUE THREAD

**Issue by renebrummel** [RedAndBundle/Cust.SpearTech#12]
[I23B022J.pdf](https://github.com/RedAndBundle/Cust.SpearTech/files/11443168/I23B022J.pdf)

**Comment by PeterV-RaB** [comment]
Custom layout made and added to repo. For comment

**Comment by renebrummel** [comment]
Invoice
-	Remove ClaimID (claim number already in the invoice) 
-	The accident date is not in the interface and showing blank, so need to add to interface
-	Rename label “ Sell To Customer” to Customer
-	Fix Task Date (it’s showing text “Task Dat” not the actual date)
-	Add Customer tax ID (think we should have it in BC already)
-	Rename document date to Invoice Date
-	Add “Remit to” above the remittance info

**Comment by PeterV-RaB** [comment]
- "Remit to" - Invoice displays what is in BC under 'Fornav Setup' > 'Payment note'. Enter "Remit to" there and invoice will show
- All other points updated
